load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "periodica_core",
    srcs = [
        "periodica/cpp/auxiliary.cpp",
        "periodica/cpp/delaunay.cpp",
        "periodica/cpp/merge_tree.cpp",
        "periodica/cpp/persistence_image.cpp",
    ],
    hdrs = [
        "periodica/cpp/auxiliary.h",
        "periodica/cpp/delaunay.h",
        "periodica/cpp/merge_tree.h",
        "periodica/cpp/persistence_image.h",
        "periodica/cpp/persistence_image_impl.h",
    ],
    copts = [
        "-std=c++20",
        "-DCGAL_CORE_USE_BOOST_BACKEND",
        "-DCGAL_NO_GMP=1",
        "-DCGAL_NO_MPFR=1",
    ],
    includes = ["periodica/cpp"],
    deps = [
        "@boost//:boost_headers",
        "@cgal//:cgal",
        "@eigen//:eigen",
        "@gudhi//:gudhi",
    ],
)

cc_binary(
    name = "_periodica.so",
    srcs = ["periodica/cpp/periodica.cpp"],
    copts = [
        "-std=c++20",
        "-fvisibility=hidden",
        "-fexceptions",
        "-DCGAL_CORE_USE_BOOST_BACKEND",
        "-DCGAL_NO_GMP=1",
        "-DCGAL_NO_MPFR=1",
    ],
    deps = [
        ":periodica_core",
        "@pybind11//:pybind11",
        "@rules_python//python/cc:current_py_cc_headers",
    ],
    linkopts = ["-Wl,-Bsymbolic"],
    linkshared = True,
)

alias(
    name = "periodica",
    actual = ":_periodica.so",
)

alias(
    name = "periodica_so",
    actual = ":_periodica.so",
)
